# Generated by Django 3.1.3 on 2020-11-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')),
                ('product', models.CharField(max_length=50, verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.order')),
            ],
        ),
    ]
