# Generated by Django 3.1.3 on 2020-11-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201119_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата реєстрації'),
        ),
    ]
